CREATE DATABASE IF NOT EXISTS agrogestor;
USE agrogestor;

CREATE TABLE IF NOT EXISTS Users (
  id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  name VARCHAR(120) NOT NULL,
  email VARCHAR(256) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'USER',
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Posts (
  id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  userId CHAR(36) NOT NULL,
  title VARCHAR(120) NOT NULL,
  description VARCHAR(1000) NULL,
  price DECIMAL(18,2) NOT NULL,
  imageUrl VARCHAR(500) NULL,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_Posts_Users FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE INDEX IF NOT EXISTS idx_posts_created ON Posts(createdAt DESC);
CREATE INDEX IF NOT EXISTS idx_users_status ON Users(status);
